### ISSUE TITLE
Full Dataset Availability Questions

### ISSUE THREAD

**Issue by bellringer27** [NetManAIOps/DejaVu#2]
Hello,
In your datasets I noticed the inclusion of your parsed metrics, but not the raw data gathered from train-ticket such as the traces.pkl file you create in your data collection scripts. I was wondering if this data would be made available in the future or not? Thanks!

**Comment by lizeyan** [comment]
The raw Train-Ticket dataset is very huge (tens of GBs), and I do not have enough free storage space on DropBox or OneDrive. I will try to find a good place to share it in a few days.

**Comment by lizeyan** [comment]
I update the raw data at https://doi.org/10.5281/zenodo.6955909
